services:
  local:
    build: .
    command: ['npm', 'run', 'docker-entrypoint']
    volumes:
      - ./scripts:/app/scripts:ro
      - ./package.json:/app/package.json:ro
      - .env:/app/.env:rw
      - ~/.ocean/ocean-contracts/artifacts:/home/nextjs/.ocean/ocean-contracts/artifacts/:cached
    ports:
      - '3000:3000'
    networks:
      ocean:
        ipv4_address: 172.16.0.99

networks:
  ocean:
    external: true
